# Generated by Django 5.2 on 2026-02-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
