# Generated by Django 5.2 on 2026-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuportfolio', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
